version: "3.9"

services:
  nextjs:
    build: ./nextjs
    container_name: nextjs_container
    environment:
      - NODE_ENV=development
    volumes:
      - ./nextjs:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: mysecretpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql
      PMA_USER: myuser
      PMA_PASSWORD: mypassword
    ports:
      - "8080:80"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx_container
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nextjs:/app
    ports:
      - "80:80"
    depends_on:
      - nextjs

  php:
    build: ./php
    container_name: php_container
    volumes:
      - ./php:/var/www/html
    depends_on:
      - mysql

volumes:
  mysql_data:
